// Generated by the i18n split. One file per namespace: a single
// message catalogue of several thousand keys is unreviewable.

import action_errors from "./action_errors.json";
import announcements from "./announcements.json";
import api_tokens from "./api_tokens.json";
import audit from "./audit.json";
import backup from "./backup.json";
import branding from "./branding.json";
import calendar from "./calendar.json";
import catalogs from "./catalogs.json";
import client_contracts from "./client_contracts.json";
import clients from "./clients.json";
import cnesst from "./cnesst.json";
import command_palette from "./command_palette.json";
import compensation from "./compensation.json";
import content from "./content.json";
import contracts from "./contracts.json";
import dashboard from "./dashboard.json";
import data_table from "./data_table.json";
import demo from "./demo.json";
import disputes from "./disputes.json";
import documents from "./documents.json";
import email_templates from "./email_templates.json";
import emails from "./emails.json";
import emergency from "./emergency.json";
import employee_file from "./employee_file.json";
import equipment from "./equipment.json";
import expenses from "./expenses.json";
import family from "./family.json";
import finance from "./finance.json";
import finance_settings from "./finance_settings.json";
import fx from "./fx.json";
import handbooks from "./handbooks.json";
import hr_documents from "./hr_documents.json";
import hr_nav from "./hr_nav.json";
import invoices from "./invoices.json";
import job_codes from "./job_codes.json";
import leave_policies from "./leave_policies.json";
import leave_windows from "./leave_windows.json";
import leaves from "./leaves.json";
import letters from "./letters.json";
import library from "./library.json";
import maintenance from "./maintenance.json";
import mandates from "./mandates.json";
import message_templates from "./message_templates.json";
import messages from "./messages.json";
import my_contracts from "./my_contracts.json";
import my_dashboard from "./my_dashboard.json";
import my_documents from "./my_documents.json";
import offboarding from "./offboarding.json";
import onboarding from "./onboarding.json";
import one_on_ones from "./one_on_ones.json";
import page_titles from "./page_titles.json";
import payments from "./payments.json";
import payouts from "./payouts.json";
import payroll from "./payroll.json";
import profile from "./profile.json";
import push from "./push.json";
import quotes from "./quotes.json";
import receipts from "./receipts.json";
import reconciliation from "./reconciliation.json";
import refunds from "./refunds.json";
import requests from "./requests.json";
import security from "./security.json";
import settings_admin from "./settings_admin.json";
import settlements from "./settlements.json";
import sidebar from "./sidebar.json";
import statistics from "./statistics.json";
import tax_decl from "./tax_decl.json";
import tax_docs from "./tax_docs.json";
import team from "./team.json";
import team_activity from "./team_activity.json";
import teams from "./teams.json";
import timeclock from "./timeclock.json";
import timeclock_settings from "./timeclock_settings.json";
import topbar from "./topbar.json";
import trainings from "./trainings.json";
import transactions from "./transactions.json";
import ui from "./ui.json";
import webhooks from "./webhooks.json";
import welcome from "./welcome.json";
import workflow from "./workflow.json";

export default {
  action_errors,
  announcements,
  api_tokens,
  audit,
  backup,
  branding,
  calendar,
  catalogs,
  client_contracts,
  clients,
  cnesst,
  command_palette,
  compensation,
  content,
  contracts,
  dashboard,
  data_table,
  demo,
  disputes,
  documents,
  email_templates,
  emails,
  emergency,
  employee_file,
  equipment,
  expenses,
  family,
  finance,
  finance_settings,
  fx,
  handbooks,
  hr_documents,
  hr_nav,
  invoices,
  job_codes,
  leave_policies,
  leave_windows,
  leaves,
  letters,
  library,
  maintenance,
  mandates,
  message_templates,
  messages,
  my_contracts,
  my_dashboard,
  my_documents,
  offboarding,
  onboarding,
  one_on_ones,
  page_titles,
  payments,
  payouts,
  payroll,
  profile,
  push,
  quotes,
  receipts,
  reconciliation,
  refunds,
  requests,
  security,
  settings_admin,
  settlements,
  sidebar,
  statistics,
  tax_decl,
  tax_docs,
  team,
  team_activity,
  teams,
  timeclock,
  timeclock_settings,
  topbar,
  trainings,
  transactions,
  ui,
  webhooks,
  welcome,
  workflow,
};
