// Generated by the i18n split. One file per namespace: a single
// message catalogue of several thousand keys is unreviewable.

import about from "./about.json";
import api_errors from "./api_errors.json";
import auth from "./auth.json";
import common from "./common.json";
import contact from "./contact.json";
import errors from "./errors.json";
import home from "./home.json";
import meta from "./meta.json";
import nav from "./nav.json";
import portal from "./portal.json";
import services from "./services.json";
import settings from "./settings.json";
import status from "./status.json";
import workflow_events from "./workflow_events.json";
import admin from "./admin";

export default {
  api_errors,
  about,
  auth,
  common,
  contact,
  errors,
  home,
  meta,
  nav,
  portal,
  services,
  settings,
  status,
  workflow_events,
  admin,
};
