// Generated by the i18n split. One file per namespace: a single
// message catalogue of several thousand keys is unreviewable.

import audit from "./audit.json";
import clients from "./clients.json";
import contracts from "./contracts.json";
import dashboard from "./dashboard.json";
import disputes from "./disputes.json";
import expenses from "./expenses.json";
import invoices from "./invoices.json";
import mandates from "./mandates.json";
import profile from "./profile.json";
import quotes from "./quotes.json";
import refunds from "./refunds.json";
import sidebar from "./sidebar.json";
import tax_decl from "./tax_decl.json";
import timeclock from "./timeclock.json";
import topbar from "./topbar.json";
import transactions from "./transactions.json";

export default {
  audit,
  clients,
  contracts,
  dashboard,
  disputes,
  expenses,
  invoices,
  mandates,
  profile,
  quotes,
  refunds,
  sidebar,
  tax_decl,
  timeclock,
  topbar,
  transactions,
};
